language: node_js
node_js:
  - "5.11"

branches:
  only:
    - master

before_script:
  - npm install -g angular-cli@latest

script:
  - ng build --prod --aot

after_script:
  - npm run sw

after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
